services:
  docs:
    image: saas_boilerplate_local_docs
    container_name: saas_boilerplate_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./saas_boilerplate:/app/saas_boilerplate:z
    ports:
      - '9000:9000'
    command: /start-docs
