# Generated by Django 5.0.8 on 2024-08-09 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='organisations', to=settings.AUTH_USER_MODEL),
        ),
    ]
